#!/usr/bin/env python3
"""
Aggregate per-endpoint metrics across multiple baseline runs and compute mean/std.

Usage:
  python ToxD4C/tools/aggregate_std_three_runs.py \
    --experiments ToxD4C/experiments/toxd4c_baseline_complete_20250903_220804 \
                 ToxD4C/experiments/toxd4c_baseline_complete_20250903_223754 \
                 ToxD4C/experiments/toxd4c_baseline_complete_20250904_094335 \
    --out_dir ToxD4C/a2_uncertainty_analysis

It expects each experiment to have checkpoints/detailed_endpoint_results.json
generated by evaluate_detailed_endpoints.py (ideally with --with_uncertainty).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List
import numpy as np
import pandas as pd


CLS_KEYS = ['accuracy', 'auc', 'f1_score', 'precision', 'recall', 'ece', 'brier']
REG_KEYS = ['r2', 'rmse', 'mae']


def load_detailed(exp_dir: Path) -> Dict:
    fp = exp_dir / 'checkpoints' / 'detailed_endpoint_results.json'
    if not fp.exists():
        raise FileNotFoundError(f'Missing {fp}. Run evaluate_detailed_endpoints.py first.')
    with open(fp, 'r') as f:
        return json.load(f)


def aggregate_classification(results_list: List[Dict]) -> pd.DataFrame:
    # Collect per-endpoint values across runs
    endpoints = set()
    for res in results_list:
        endpoints.update(res.get('classification_endpoints', {}).keys())
    endpoints = sorted(list(endpoints))

    rows = []
    for ep in endpoints:
        row = {'Endpoint': ep}
        # collect values per key
        for key in CLS_KEYS:
            values = []
            for res in results_list:
                ep_metrics = res.get('classification_endpoints', {}).get(ep, {})
                v = ep_metrics.get(key)
                if v is not None:
                    values.append(float(v))
            if values:
                row[f'{key}_mean'] = float(np.mean(values))
                row[f'{key}_std'] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
                row[f'{key}_n'] = len(values)
            else:
                row[f'{key}_mean'] = None
                row[f'{key}_std'] = None
                row[f'{key}_n'] = 0
        rows.append(row)
    return pd.DataFrame(rows)


def aggregate_regression(results_list: List[Dict]) -> pd.DataFrame:
    endpoints = set()
    for res in results_list:
        endpoints.update(res.get('regression_endpoints', {}).keys())
    endpoints = sorted(list(endpoints))

    rows = []
    for ep in endpoints:
        row = {'Endpoint': ep}
        for key in REG_KEYS:
            values = []
            for res in results_list:
                ep_metrics = res.get('regression_endpoints', {}).get(ep, {})
                v = ep_metrics.get(key)
                if v is not None:
                    values.append(float(v))
            if values:
                row[f'{key}_mean'] = float(np.mean(values))
                row[f'{key}_std'] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
                row[f'{key}_n'] = len(values)
            else:
                row[f'{key}_mean'] = None
                row[f'{key}_std'] = None
                row[f'{key}_n'] = 0
        rows.append(row)
    return pd.DataFrame(rows)


def aggregate_summaries(results_list: List[Dict]) -> pd.DataFrame:
    rows = []
    # Build a single row per summary key with mean/std across runs
    # classification
    cls_keys = [('classification', 'avg_accuracy'), ('classification', 'avg_auc'),
                ('classification', 'avg_f1_score'), ('classification', 'avg_ece'),
                ('classification', 'avg_brier')]
    reg_keys = [('regression', 'avg_r2'), ('regression', 'avg_rmse'), ('regression', 'avg_mae')]

    for group, key in cls_keys + reg_keys:
        values = []
        for res in results_list:
            grp = res.get('summary', {}).get(group, {})
            v = grp.get(key)
            if v is not None:
                values.append(float(v))
        rows.append({
            'metric': f'{group}.{key}',
            'mean': float(np.mean(values)) if values else None,
            'std': float(np.std(values, ddof=1)) if len(values) > 1 else (0.0 if values else None),
            'n': len(values)
        })
    return pd.DataFrame(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--experiments', nargs='+', required=True, help='Experiment directories to aggregate')
    ap.add_argument('--out_dir', default='ToxD4C/a2_uncertainty_analysis', help='Output directory')
    args = ap.parse_args()

    exp_dirs = [Path(p) for p in args.experiments]
    results = [load_detailed(p) for p in exp_dirs]

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df_cls = aggregate_classification(results)
    df_reg = aggregate_regression(results)
    df_sum = aggregate_summaries(results)

    df_cls.to_csv(out_dir / 'baseline_three_runs_classification_mean_std.csv', index=False)
    df_reg.to_csv(out_dir / 'baseline_three_runs_regression_mean_std.csv', index=False)
    df_sum.to_csv(out_dir / 'baseline_three_runs_summary_mean_std.csv', index=False)

    # Also save JSON
    (out_dir / 'baseline_three_runs_agg.json').write_text(json.dumps({
        'experiments': [str(p) for p in exp_dirs],
        'classification': df_cls.to_dict(orient='records'),
        'regression': df_reg.to_dict(orient='records'),
        'summary': df_sum.to_dict(orient='records')
    }, indent=2))

    print('Saved:')
    print(out_dir / 'baseline_three_runs_classification_mean_std.csv')
    print(out_dir / 'baseline_three_runs_regression_mean_std.csv')
    print(out_dir / 'baseline_three_runs_summary_mean_std.csv')


if __name__ == '__main__':
    main()

